jenkins:
  build: jenkins
  links:
   - sonarqube
  ports:
    - "80:8080"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  environment:
    - JAVA_OPTS=-Xmx1536m
    - ADMIN_PASSWORD=secret
  mem_limit: 2147483648
sonarqube:
  build: sonarqube
  links:
   - sonarqube-database
  ports:
    - "9000:9000"
  environment:
    - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube-database/sonar
    - WEB_JAVA_OPTS=-Xmx384m
    - SEARCH_JAVA_OPTS=-Xmx384m
    - ADMIN_PASSWORD=secret
  mem_limit: 1610612736
sonarqube-database:
  image: postgres
  environment:
    - POSTGRES_USER=sonar
    - POSTGRES_PASSWORD=sonar
  mem_limit: 268435456
